image: haskell:8.4.4

before_script:
  - stack --system-ghc build

pages:
  stage: deploy
  script:
    - stack --system-ghc exec blog build
  artifacts:
    paths:
    - public
  only:
    - master
  
test:
  stage: test
  script:
    - stack --system-ghc exec blog build
  only:
    - develop
