name: GitHub Personal Site
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.8.3"]
        stack: ["2.3.1"]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Setup Haskell
        uses: actions/setup-haskell@v1.1.2
        with:
            ghc-version: ${{ matrix.ghc }}
            cabal-version: ${{ matrix.cabal }}
            stack-version: ${{ matrix.stack }}
      -
        name: Cache ~/.stack and _cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
            _cache
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - run: stack setup
      - run: stack --system-ghc build --only-dependencies
      - run: stack --system-ghc build --test --bench --no-run-tests --no-run-benchmarks
      - run: stack --system-ghc exec blog build
      -
        name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/deploy-pages'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}